### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by arturnista** [GrupoOperacionalRDO/WebThreshGame_gamejam#1]
Hello collegues,
Could you kindly please make it work?

Thanks and best regards,
Artur Nista

**Comment by arturnista** [comment]
Hello,
It's not working yet, is this feature in your backlog?

Thanks and best regards,
Artur Nista

**Comment by math-eusp** [comment]
Put the **culpation** in @lorekqt because yes

**Comment by arturnista** [comment]
Thanks for your reply!

@lorekqt are you planning to fix this issue?
@Moharu are you still working on this project?
@math-eusp is this real life?
@arturnista you are the best programmer. when u are not programming kek

Thanks

**Comment by math-eusp** [comment]
it's just fanta sea
my job here is done 
**throws a ninja smoke**

**Comment by math-eusp** [comment]
LOL É UMA MERDA
XANZ GOSTA MEMO É DE MULHER
ULY TB
TRIK E TROK SÃO A MESMA PESSOA
